// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID    string   `json:"id"`
	Name  string   `json:"name"`
	Dir   string   `json:"dir"`
	Pages []string `json:"pages"`
}

type BookInitInput struct {
	Dir string `json:"dir"`
}

type BookInput struct {
	Name *string `json:"name"`
}

type BookMin struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Library struct {
	ID    string     `json:"id"`
	Name  string     `json:"name"`
	Books []*BookMin `json:"books"`
}

type LibraryInput struct {
	Name    *string `json:"name"`
	RootDir string  `json:"rootDir"`
}

type LibraryMin struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
